name: Delete

on:
  workflow_dispatch:
    description: '手动触发一次编译'
  schedule:
    - cron: 0 1 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: 删除工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2

    - name: 删除旧的releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}