name: 删除Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: 删除工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2