name: 360T7

on:
  schedule:
    - cron: 0 16 2-8 * 6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 删除工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 5

    - name: 删除旧的releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}