name: Remove

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 1,15 * *

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-22.04
    steps:
    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1

    - name: 移除旧项目
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}