name: Remove

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 1,15 * *

jobs:
  Delete-Workflow:
    runs-on: ubuntu-22.04
    steps:
    - name: 删除工作流
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 1
        delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
